# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/Atm-Project/QT_designer/admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_window(object):
    def setupUi(self, admin_window):
        admin_window.setObjectName("admin_window")
        admin_window.resize(480, 600)
        self.centralwidget = QtWidgets.QWidget(admin_window)
        self.centralwidget.setObjectName("centralwidget")
        self.adminwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.adminwdw_lbl_heading.setGeometry(QtCore.QRect(120, 60, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.adminwdw_lbl_heading.setFont(font)
        self.adminwdw_lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.adminwdw_lbl_heading.setObjectName("adminwdw_lbl_heading")
        self.adminwdw_lbl_ADid = QtWidgets.QLabel(self.centralwidget)
        self.adminwdw_lbl_ADid.setGeometry(QtCore.QRect(140, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adminwdw_lbl_ADid.setFont(font)
        self.adminwdw_lbl_ADid.setObjectName("adminwdw_lbl_ADid")
        self.adminwdw_lbl_ADpassword = QtWidgets.QLabel(self.centralwidget)
        self.adminwdw_lbl_ADpassword.setGeometry(QtCore.QRect(140, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adminwdw_lbl_ADpassword.setFont(font)
        self.adminwdw_lbl_ADpassword.setObjectName("adminwdw_lbl_ADpassword")
        self.adminwdw_btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_login.setGeometry(QtCore.QRect(170, 330, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adminwdw_btn_login.setFont(font)
        self.adminwdw_btn_login.setObjectName("adminwdw_btn_login")
        self.adminwdw_linedit_ADid = QtWidgets.QLineEdit(self.centralwidget)
        self.adminwdw_linedit_ADid.setGeometry(QtCore.QRect(140, 180, 211, 31))
        self.adminwdw_linedit_ADid.setObjectName("adminwdw_linedit_ADid")
        self.adminwdw_linedit_ADpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.adminwdw_linedit_ADpassword.setGeometry(QtCore.QRect(140, 260, 211, 31))
        self.adminwdw_linedit_ADpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adminwdw_linedit_ADpassword.setObjectName("adminwdw_linedit_ADpassword")
        self.adminwdw_btn_returnmain = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_returnmain.setGeometry(QtCore.QRect(90, 440, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adminwdw_btn_returnmain.setFont(font)
        self.adminwdw_btn_returnmain.setObjectName("adminwdw_btn_returnmain")
        self.adminwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_exit.setGeometry(QtCore.QRect(260, 440, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adminwdw_btn_exit.setFont(font)
        self.adminwdw_btn_exit.setObjectName("adminwdw_btn_exit")
        self.adminwdw_lbl_warning = QtWidgets.QLabel(self.centralwidget)
        self.adminwdw_lbl_warning.setGeometry(QtCore.QRect(140, 300, 211, 16))
        self.adminwdw_lbl_warning.setStyleSheet("color: rgb(255, 38, 0);")
        self.adminwdw_lbl_warning.setText("")
        self.adminwdw_lbl_warning.setObjectName("adminwdw_lbl_warning")
        admin_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(admin_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        admin_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(admin_window)
        self.statusbar.setObjectName("statusbar")
        admin_window.setStatusBar(self.statusbar)

        self.retranslateUi(admin_window)
        self.adminwdw_btn_exit.clicked.connect(admin_window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(admin_window)

    def retranslateUi(self, admin_window):
        _translate = QtCore.QCoreApplication.translate
        admin_window.setWindowTitle(_translate("admin_window", "Admin Window"))
        self.adminwdw_lbl_heading.setText(_translate("admin_window", "Administrative Login "))
        self.adminwdw_lbl_ADid.setText(_translate("admin_window", "ID:"))
        self.adminwdw_lbl_ADpassword.setText(_translate("admin_window", "Password:"))
        self.adminwdw_btn_login.setText(_translate("admin_window", "LOGIN"))
        self.adminwdw_btn_returnmain.setText(_translate("admin_window", "Main Window"))
        self.adminwdw_btn_exit.setText(_translate("admin_window", "Exit"))
