# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/Atm-Project/QT_designer/customer_login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customer_login_window(object):
    def setupUi(self, customer_login_window):
        customer_login_window.setObjectName("customer_login_window")
        customer_login_window.resize(480, 600)
        self.centralwidget = QtWidgets.QWidget(customer_login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.csloginwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.csloginwdw_lbl_heading.setGeometry(QtCore.QRect(120, 60, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.csloginwdw_lbl_heading.setFont(font)
        self.csloginwdw_lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.csloginwdw_lbl_heading.setObjectName("csloginwdw_lbl_heading")
        self.csloginwdw_lbl_ADid = QtWidgets.QLabel(self.centralwidget)
        self.csloginwdw_lbl_ADid.setGeometry(QtCore.QRect(140, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csloginwdw_lbl_ADid.setFont(font)
        self.csloginwdw_lbl_ADid.setObjectName("csloginwdw_lbl_ADid")
        self.csloginwdw_lbl_ADpassword = QtWidgets.QLabel(self.centralwidget)
        self.csloginwdw_lbl_ADpassword.setGeometry(QtCore.QRect(140, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csloginwdw_lbl_ADpassword.setFont(font)
        self.csloginwdw_lbl_ADpassword.setObjectName("csloginwdw_lbl_ADpassword")
        self.csloginwdw_btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.csloginwdw_btn_login.setGeometry(QtCore.QRect(170, 330, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csloginwdw_btn_login.setFont(font)
        self.csloginwdw_btn_login.setObjectName("csloginwdw_btn_login")
        self.csloginwdw_linedit_ADid = QtWidgets.QLineEdit(self.centralwidget)
        self.csloginwdw_linedit_ADid.setGeometry(QtCore.QRect(140, 180, 211, 31))
        self.csloginwdw_linedit_ADid.setObjectName("csloginwdw_linedit_ADid")
        self.csloginwdw_linedit_ADpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.csloginwdw_linedit_ADpassword.setGeometry(QtCore.QRect(140, 260, 211, 31))
        self.csloginwdw_linedit_ADpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.csloginwdw_linedit_ADpassword.setObjectName("csloginwdw_linedit_ADpassword")
        self.csloginwdw_btn_returnmain = QtWidgets.QPushButton(self.centralwidget)
        self.csloginwdw_btn_returnmain.setGeometry(QtCore.QRect(90, 440, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csloginwdw_btn_returnmain.setFont(font)
        self.csloginwdw_btn_returnmain.setObjectName("csloginwdw_btn_returnmain")
        self.csloginwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.csloginwdw_btn_exit.setGeometry(QtCore.QRect(260, 440, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csloginwdw_btn_exit.setFont(font)
        self.csloginwdw_btn_exit.setObjectName("csloginwdw_btn_exit")
        self.csloginwdw_lbl_warning = QtWidgets.QLabel(self.centralwidget)
        self.csloginwdw_lbl_warning.setGeometry(QtCore.QRect(140, 300, 211, 16))
        self.csloginwdw_lbl_warning.setStyleSheet("color: rgb(255, 38, 0);")
        self.csloginwdw_lbl_warning.setText("")
        self.csloginwdw_lbl_warning.setObjectName("csloginwdw_lbl_warning")
        customer_login_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(customer_login_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        customer_login_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(customer_login_window)
        self.statusbar.setObjectName("statusbar")
        customer_login_window.setStatusBar(self.statusbar)

        self.retranslateUi(customer_login_window)
        self.csloginwdw_btn_exit.clicked.connect(customer_login_window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(customer_login_window)

    def retranslateUi(self, customer_login_window):
        _translate = QtCore.QCoreApplication.translate
        customer_login_window.setWindowTitle(_translate("customer_login_window", "Customer Login Window"))
        self.csloginwdw_lbl_heading.setText(_translate("customer_login_window", "Customer Login "))
        self.csloginwdw_lbl_ADid.setText(_translate("customer_login_window", "Customer ID:"))
        self.csloginwdw_lbl_ADpassword.setText(_translate("customer_login_window", "Password:"))
        self.csloginwdw_btn_login.setText(_translate("customer_login_window", "LOGIN"))
        self.csloginwdw_btn_returnmain.setText(_translate("customer_login_window", "Main Window"))
        self.csloginwdw_btn_exit.setText(_translate("customer_login_window", "Exit"))
