# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/Atm-Project/QT_designer/customer_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customer_main_window(object):
    def setupUi(self, customer_main_window):
        customer_main_window.setObjectName("customer_main_window")
        customer_main_window.setWindowModality(QtCore.Qt.ApplicationModal)
        customer_main_window.resize(600, 700)
        customer_main_window.setMinimumSize(QtCore.QSize(600, 700))
        customer_main_window.setMaximumSize(QtCore.QSize(600, 700))
        customer_main_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        customer_main_window.setAcceptDrops(False)
        customer_main_window.setStyleSheet("background-color: rgb(5, 130, 202);")
        customer_main_window.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(customer_main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.csmainwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.csmainwdw_lbl_heading.setGeometry(QtCore.QRect(50, 10, 491, 81))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_lbl_heading.setFont(font)
        self.csmainwdw_lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.csmainwdw_lbl_heading.setObjectName("csmainwdw_lbl_heading")
        self.csmainwdw_btn_getcash = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_getcash.setGeometry(QtCore.QRect(110, 330, 180, 50))
        self.csmainwdw_btn_getcash.setMinimumSize(QtCore.QSize(180, 50))
        self.csmainwdw_btn_getcash.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_btn_getcash.setFont(font)
        self.csmainwdw_btn_getcash.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.csmainwdw_btn_getcash.setObjectName("csmainwdw_btn_getcash")
        self.csmainwdw_btn_returnmain = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_returnmain.setGeometry(QtCore.QRect(110, 540, 180, 70))
        self.csmainwdw_btn_returnmain.setMinimumSize(QtCore.QSize(180, 70))
        self.csmainwdw_btn_returnmain.setMaximumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_btn_returnmain.setFont(font)
        self.csmainwdw_btn_returnmain.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.csmainwdw_btn_returnmain.setObjectName("csmainwdw_btn_returnmain")
        self.csmainwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_exit.setGeometry(QtCore.QRect(310, 540, 180, 70))
        self.csmainwdw_btn_exit.setMinimumSize(QtCore.QSize(180, 70))
        self.csmainwdw_btn_exit.setMaximumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_btn_exit.setFont(font)
        self.csmainwdw_btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.csmainwdw_btn_exit.setObjectName("csmainwdw_btn_exit")
        self.csmainwdw_btn_deposit = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_deposit.setGeometry(QtCore.QRect(310, 330, 180, 50))
        self.csmainwdw_btn_deposit.setMinimumSize(QtCore.QSize(180, 50))
        self.csmainwdw_btn_deposit.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_btn_deposit.setFont(font)
        self.csmainwdw_btn_deposit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.csmainwdw_btn_deposit.setObjectName("csmainwdw_btn_deposit")
        self.csmainwdw_btn_moneyup = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_moneyup.setGeometry(QtCore.QRect(440, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.csmainwdw_btn_moneyup.setFont(font)
        self.csmainwdw_btn_moneyup.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.csmainwdw_btn_moneyup.setObjectName("csmainwdw_btn_moneyup")
        self.csmainwdw_btn_moneydown = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_moneydown.setGeometry(QtCore.QRect(130, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.csmainwdw_btn_moneydown.setFont(font)
        self.csmainwdw_btn_moneydown.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.csmainwdw_btn_moneydown.setObjectName("csmainwdw_btn_moneydown")
        self.csmainwdw_spinbox_money = QtWidgets.QSpinBox(self.centralwidget)
        self.csmainwdw_spinbox_money.setGeometry(QtCore.QRect(230, 260, 160, 40))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.csmainwdw_spinbox_money.setFont(font)
        self.csmainwdw_spinbox_money.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.csmainwdw_spinbox_money.setStyleSheet("font: 24pt \".AppleSystemUIFont\";\n"
"background-color: rgb(236, 236, 236);")
        self.csmainwdw_spinbox_money.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.csmainwdw_spinbox_money.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csmainwdw_spinbox_money.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.csmainwdw_spinbox_money.setSuffix("")
        self.csmainwdw_spinbox_money.setMinimum(0)
        self.csmainwdw_spinbox_money.setMaximum(1000000)
        self.csmainwdw_spinbox_money.setSingleStep(100)
        self.csmainwdw_spinbox_money.setProperty("value", 0)
        self.csmainwdw_spinbox_money.setObjectName("csmainwdw_spinbox_money")
        self.csmainwdw_btn_statement = QtWidgets.QPushButton(self.centralwidget)
        self.csmainwdw_btn_statement.setGeometry(QtCore.QRect(109, 450, 381, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_btn_statement.setFont(font)
        self.csmainwdw_btn_statement.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.csmainwdw_btn_statement.setObjectName("csmainwdw_btn_statement")
        self.csmainwdw_lbl_resultmessage = QtWidgets.QLabel(self.centralwidget)
        self.csmainwdw_lbl_resultmessage.setGeometry(QtCore.QRect(110, 390, 381, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_lbl_resultmessage.setFont(font)
        self.csmainwdw_lbl_resultmessage.setStyleSheet("")
        self.csmainwdw_lbl_resultmessage.setText("")
        self.csmainwdw_lbl_resultmessage.setObjectName("csmainwdw_lbl_resultmessage")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(91, 110, 441, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.csmainwdw_lbl_CSname_heading = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_lbl_CSname_heading.setFont(font)
        self.csmainwdw_lbl_CSname_heading.setObjectName("csmainwdw_lbl_CSname_heading")
        self.verticalLayout.addWidget(self.csmainwdw_lbl_CSname_heading)
        self.csmainwdw_lbl_CSID_heading = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_lbl_CSID_heading.setFont(font)
        self.csmainwdw_lbl_CSID_heading.setObjectName("csmainwdw_lbl_CSID_heading")
        self.verticalLayout.addWidget(self.csmainwdw_lbl_CSID_heading)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.csmainwdw_lbl_CSname_show = QtWidgets.QLabel(self.layoutWidget)
        self.csmainwdw_lbl_CSname_show.setText("")
        self.csmainwdw_lbl_CSname_show.setObjectName("csmainwdw_lbl_CSname_show")
        self.verticalLayout_2.addWidget(self.csmainwdw_lbl_CSname_show)
        self.csmainwdw_lbl_CSID_show = QtWidgets.QLabel(self.layoutWidget)
        self.csmainwdw_lbl_CSID_show.setText("")
        self.csmainwdw_lbl_CSID_show.setObjectName("csmainwdw_lbl_CSID_show")
        self.verticalLayout_2.addWidget(self.csmainwdw_lbl_CSID_show)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 180, 441, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.csmainwdw_lbl_balanceheading = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.csmainwdw_lbl_balanceheading.setFont(font)
        self.csmainwdw_lbl_balanceheading.setObjectName("csmainwdw_lbl_balanceheading")
        self.horizontalLayout_2.addWidget(self.csmainwdw_lbl_balanceheading)
        self.csmainwdw_lbl_balanceshow = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csmainwdw_lbl_balanceshow.setFont(font)
        self.csmainwdw_lbl_balanceshow.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.csmainwdw_lbl_balanceshow.setText("")
        self.csmainwdw_lbl_balanceshow.setTextFormat(QtCore.Qt.AutoText)
        self.csmainwdw_lbl_balanceshow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csmainwdw_lbl_balanceshow.setObjectName("csmainwdw_lbl_balanceshow")
        self.horizontalLayout_2.addWidget(self.csmainwdw_lbl_balanceshow)
        customer_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(customer_main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        customer_main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(customer_main_window)
        self.statusbar.setObjectName("statusbar")
        customer_main_window.setStatusBar(self.statusbar)

        self.retranslateUi(customer_main_window)
        self.csmainwdw_btn_moneyup.clicked['bool'].connect(self.csmainwdw_spinbox_money.stepUp) # type: ignore
        self.csmainwdw_btn_moneydown.clicked['bool'].connect(self.csmainwdw_spinbox_money.stepDown) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(customer_main_window)

    def retranslateUi(self, customer_main_window):
        _translate = QtCore.QCoreApplication.translate
        customer_main_window.setWindowTitle(_translate("customer_main_window", "Customer Main Window"))
        self.csmainwdw_lbl_heading.setText(_translate("customer_main_window", "Account Operations"))
        self.csmainwdw_btn_getcash.setText(_translate("customer_main_window", "GET CASH"))
        self.csmainwdw_btn_returnmain.setText(_translate("customer_main_window", "Back"))
        self.csmainwdw_btn_exit.setText(_translate("customer_main_window", "Exit"))
        self.csmainwdw_btn_deposit.setText(_translate("customer_main_window", "DEPOSIT"))
        self.csmainwdw_btn_moneyup.setText(_translate("customer_main_window", "+"))
        self.csmainwdw_btn_moneydown.setText(_translate("customer_main_window", "-"))
        self.csmainwdw_btn_statement.setText(_translate("customer_main_window", "VIEW BANK STATEMENT"))
        self.csmainwdw_lbl_CSname_heading.setText(_translate("customer_main_window", "Customer Name:"))
        self.csmainwdw_lbl_CSID_heading.setText(_translate("customer_main_window", "Customer ID:"))
        self.csmainwdw_lbl_balanceheading.setText(_translate("customer_main_window", "Your current balance:"))
