# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\qwert\OneDrive\Belgeler\GitHub\Atm-Project\QT_designer\customer_statement_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customer_statement_window(object):
    def setupUi(self, customer_statement_window):
        customer_statement_window.setObjectName("customer_statement_window")
        customer_statement_window.setWindowModality(QtCore.Qt.ApplicationModal)
        customer_statement_window.resize(480, 600)
        customer_statement_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        customer_statement_window.setAcceptDrops(False)
        customer_statement_window.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(customer_statement_window)
        self.centralwidget.setObjectName("centralwidget")
        self.csstatementwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.csstatementwdw_lbl_heading.setGeometry(QtCore.QRect(40, 10, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.csstatementwdw_lbl_heading.setFont(font)
        self.csstatementwdw_lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.csstatementwdw_lbl_heading.setObjectName("csstatementwdw_lbl_heading")
        self.csstatementwdw_btn_returnmain = QtWidgets.QPushButton(self.centralwidget)
        self.csstatementwdw_btn_returnmain.setGeometry(QtCore.QRect(40, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csstatementwdw_btn_returnmain.setFont(font)
        self.csstatementwdw_btn_returnmain.setObjectName("csstatementwdw_btn_returnmain")
        self.csstatementwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.csstatementwdw_btn_exit.setGeometry(QtCore.QRect(320, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csstatementwdw_btn_exit.setFont(font)
        self.csstatementwdw_btn_exit.setObjectName("csstatementwdw_btn_exit")
        self.csstatementwdw_lbl_balanceheading = QtWidgets.QLabel(self.centralwidget)
        self.csstatementwdw_lbl_balanceheading.setGeometry(QtCore.QRect(40, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csstatementwdw_lbl_balanceheading.setFont(font)
        self.csstatementwdw_lbl_balanceheading.setObjectName("csstatementwdw_lbl_balanceheading")
        self.csstatementwdw_lbl_balanceshow = QtWidgets.QLabel(self.centralwidget)
        self.csstatementwdw_lbl_balanceshow.setGeometry(QtCore.QRect(250, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csstatementwdw_lbl_balanceshow.setFont(font)
        self.csstatementwdw_lbl_balanceshow.setTextFormat(QtCore.Qt.AutoText)
        self.csstatementwdw_lbl_balanceshow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csstatementwdw_lbl_balanceshow.setObjectName("csstatementwdw_lbl_balanceshow")
        self.csstatementwdw_txt_statement = QtWidgets.QTextBrowser(self.centralwidget)
        self.csstatementwdw_txt_statement.setGeometry(QtCore.QRect(40, 140, 411, 341))
        self.csstatementwdw_txt_statement.setObjectName("csstatementwdw_txt_statement")
        self.csstatementwdw_btn_returnmain_2 = QtWidgets.QPushButton(self.centralwidget)
        self.csstatementwdw_btn_returnmain_2.setGeometry(QtCore.QRect(180, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.csstatementwdw_btn_returnmain_2.setFont(font)
        self.csstatementwdw_btn_returnmain_2.setObjectName("csstatementwdw_btn_returnmain_2")
        customer_statement_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(customer_statement_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        customer_statement_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(customer_statement_window)
        self.statusbar.setObjectName("statusbar")
        customer_statement_window.setStatusBar(self.statusbar)

        self.retranslateUi(customer_statement_window)
        self.csstatementwdw_btn_exit.clicked.connect(customer_statement_window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(customer_statement_window)

    def retranslateUi(self, customer_statement_window):
        _translate = QtCore.QCoreApplication.translate
        customer_statement_window.setWindowTitle(_translate("customer_statement_window", "Customer Bank Statement"))
        self.csstatementwdw_lbl_heading.setText(_translate("customer_statement_window", "Welcome to the Bank Statement"))
        self.csstatementwdw_btn_returnmain.setText(_translate("customer_statement_window", "Main Window"))
        self.csstatementwdw_btn_exit.setText(_translate("customer_statement_window", "Exit"))
        self.csstatementwdw_lbl_balanceheading.setText(_translate("customer_statement_window", "Your current balance:"))
        self.csstatementwdw_lbl_balanceshow.setText(_translate("customer_statement_window", "0 €"))
        self.csstatementwdw_txt_statement.setHtml(_translate("customer_statement_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csstatementwdw_btn_returnmain_2.setText(_translate("customer_statement_window", "Customer Page"))
