# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/Atm-Project/QT_designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_open_window(object):
    def setupUi(self, open_window):
        open_window.setObjectName("open_window")
        open_window.resize(600, 700)
        open_window.setMinimumSize(QtCore.QSize(600, 700))
        open_window.setMaximumSize(QtCore.QSize(600, 16777215))
        open_window.setStyleSheet("background-color: rgb(5, 130, 202);")
        self.centralwidget = QtWidgets.QWidget(open_window)
        self.centralwidget.setObjectName("centralwidget")
        self.openwdw_lbl_welcome = QtWidgets.QLabel(self.centralwidget)
        self.openwdw_lbl_welcome.setGeometry(QtCore.QRect(30, 60, 541, 111))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_lbl_welcome.setFont(font)
        self.openwdw_lbl_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.openwdw_lbl_welcome.setObjectName("openwdw_lbl_welcome")
        self.openwdw_btn_CSLogin = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_CSLogin.setGeometry(QtCore.QRect(151, 221, 271, 71))
        self.openwdw_btn_CSLogin.setMinimumSize(QtCore.QSize(271, 71))
        self.openwdw_btn_CSLogin.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_CSLogin.setFont(font)
        self.openwdw_btn_CSLogin.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.openwdw_btn_CSLogin.setObjectName("openwdw_btn_CSLogin")
        self.openwdw_btn_ADLogin = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_ADLogin.setGeometry(QtCore.QRect(150, 320, 271, 71))
        self.openwdw_btn_ADLogin.setMinimumSize(QtCore.QSize(271, 71))
        self.openwdw_btn_ADLogin.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_ADLogin.setFont(font)
        self.openwdw_btn_ADLogin.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 100, 148);\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}\n"
"")
        self.openwdw_btn_ADLogin.setObjectName("openwdw_btn_ADLogin")
        self.openwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_exit.setGeometry(QtCore.QRect(200, 460, 180, 70))
        self.openwdw_btn_exit.setMinimumSize(QtCore.QSize(180, 70))
        self.openwdw_btn_exit.setMaximumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_exit.setFont(font)
        self.openwdw_btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.openwdw_btn_exit.setObjectName("openwdw_btn_exit")
        open_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(open_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        open_window.setMenuBar(self.menubar)

        self.retranslateUi(open_window)
        QtCore.QMetaObject.connectSlotsByName(open_window)

    def retranslateUi(self, open_window):
        _translate = QtCore.QCoreApplication.translate
        open_window.setWindowTitle(_translate("open_window", "MainWindow"))
        self.openwdw_lbl_welcome.setText(_translate("open_window", "Welcome to the Banking App"))
        self.openwdw_btn_CSLogin.setText(_translate("open_window", "CUSTOMER LOGIN"))
        self.openwdw_btn_ADLogin.setText(_translate("open_window", "ADMIN LOGIN"))
        self.openwdw_btn_exit.setText(_translate("open_window", "EXIT"))
